//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSWE.Models.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order1
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ShipName { get; set; }
        public string ShipMobile { get; set; }
        public string ShipAddress { get; set; }
        public string ShipEmail { get; set; }
    }
}
