//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSWE.Models.Enity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Img { get; set; }
        public string Img2 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string BestSeller { get; set; }
        public Nullable<int> Category { get; set; }
    }
}
